name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    needs: [deploy-macos, deploy-linux, deploy-windows]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 for Scala
        uses: olafurpg/setup-scala@v10
      - name: Test and publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: sbt test publish

  deploy-macos:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export PUBLISH_VERSION="$(git describe --abbrev=0 --tags|cut -c2-)"
          curl -u$BINTRAY_USER:$BINTRAY_PASS https://api.bintray.com/content/lightbend/generic/akkaserverless-codegen/$PUBLISH_VERSION/akkasls-codegen-js-x86_64-apple-darwin-$PUBLISH_VERSION?publish=1 --upload-file js-gen-cli/target/native-image/akkasls-codegen-js

  deploy-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export PUBLISH_VERSION="$(git describe --abbrev=0 --tags|cut -c2-)"
          curl -u$BINTRAY_USER:$BINTRAY_PASS https://api.bintray.com/content/lightbend/generic/akkaserverless-codegen/$PUBLISH_VERSION/akkasls-codegen-js-x86_64-unknown-linux-gnu-$PUBLISH_VERSION?publish=1 --upload-file js-gen-cli/target/native-image/akkasls-codegen-js

  deploy-windows:
    runs-on: windows-latest

    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v2
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        shell: bash
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        shell: bash
        run: |
          export PUBLISH_VERSION="$(git describe --abbrev=0 --tags|cut -c2-)"
          curl -u$BINTRAY_USER:$BINTRAY_PASS https://api.bintray.com/content/lightbend/generic/akkaserverless-codegen/$PUBLISH_VERSION/akkasls-codegen-js-x86_64-pc-windows-gnu-$PUBLISH_VERSION.exe?publish=1 --upload-file js-gen-cli/target/native-image/akkasls-codegen-js.exe
